# Workflow to build and release project artifacts
# This workflow is manually triggered via the GitHub UI

name: Build and Release

on:
  # Trigger on manual dispatch
  workflow_dispatch

# Permissions needed for the workflow
permissions:
  contents: write  # Allows the workflow to write to the repository (create tags)
  packages: write  # Allows the workflow to write to GitHub Packages (for Docker images)

jobs:
  # Job to generate a new version tag
  tagging:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tag.outputs.new_tag }}  # Output the new tag to be used by other jobs

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4  # Check out the repository code

      - name: Generate Tag
        id: tag
        uses: tschm/cradle/actions/tag@v0.4.0  # Custom action to generate a new tag
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication


  # Job to build and publish Docker container (only included if use_docker is true)
  docker:
    runs-on: ubuntu-latest
    needs: build  # This job depends on the build job
    steps:

      - name: "Build and publish the Container"
        uses: tschm/cradle/actions/docker@v0.4.0  # Custom action to build and publish Docker container
        with:
          github_actor: ${{ github.actor }}  # GitHub username
          github_repository: ${{ github.repository }}  # Repository name
          tag: ${{ needs.tagging.outputs.new_tag }}  # Tag from the tagging job
          github_token: ${{ secrets.github_token }}  # GitHub token for authentication



  # Job to build and publish LaTeX document (only included if use_latex is true)
  latex:
    runs-on: ubuntu-latest
    needs: tagging  # This job depends on the tagging job
    steps:
      - name: "Output tag"
        run: |
          echo "Tag: ${{ needs.tagging.outputs.new_tag }}"  # Print the new tag

      - name: "Build and publish the LaTeX document"
        uses: tschm/cradle/actions/latex@v0.4.0  # Custom action to build LaTeX documents
        with:
          paper: paper/document.tex  # Path to the LaTeX document to build
          tag: ${{ needs.tagging.outputs.new_tag }}  # Tag from the tagging job


  # Job to display debugging information
  debug:
    runs-on: ubuntu-latest
    needs: tagging  # This job depends on the tagging job
    steps:
      - name: Output
        run: |
          echo "Repository ${{ github.repository }}"  # Print the repository name
          echo "Tag ${{ needs.tagging.outputs.new_tag }}"  # Print the new tag
